workflows:
  ionic-capacitor-ios-build:
    name: Ionic Capacitor iOS Build
    instance_type: mac_mini_m1
    
    environment:
      node: v20.10.0
      xcode: latest
      vars:
        BUNDLE_ID: online.regionalhomeforgirls.larea
      
    scripts:
      - name: Install project dependencies
        script: |
          npm install
          
      - name: Create simple test web app
        script: |
          mkdir -p www
          cat > www/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Test WebView App</title>
            <style>
              * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                color: white;
                text-align: center;
                padding: 20px;
              }
              .container {
                max-width: 600px;
              }
              h1 {
                font-size: 2.5rem;
                margin-bottom: 20px;
              }
              p {
                font-size: 1.2rem;
                margin-bottom: 30px;
                opacity: 0.9;
              }
              .button {
                display: inline-block;
                padding: 15px 30px;
                background: white;
                color: #667eea;
                text-decoration: none;
                border-radius: 50px;
                font-weight: bold;
                transition: transform 0.2s;
              }
              .button:hover {
                transform: scale(1.05);
              }
              .status {
                margin-top: 40px;
                padding: 20px;
                background: rgba(255,255,255,0.1);
                border-radius: 10px;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>🎉 iOS App Test</h1>
              <p>Your iOS WebView app is working perfectly!</p>
              <a href="https://www.example.com" class="button">Visit Example Site</a>
              
              <div class="status">
                <p><strong>Build Status:</strong> ✅ Success</p>
                <p><strong>Platform:</strong> iOS (Capacitor)</p>
                <p><strong>Ready to customize!</strong></p>
              </div>
            </div>
            
            <script>
              // Test that JavaScript works
              console.log('WebView app loaded successfully!');
              
              // Add click event
              document.querySelector('.button').addEventListener('click', function(e) {
                console.log('Button clicked!');
              });
            </script>
          </body>
          </html>
          EOF
          
      - name: Sync Capacitor to iOS
        script: |
          npx cap sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      - name: Build iOS app (simulator)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
          
    artifacts:
      - ios/App/build/Build/Products/**/*.app
