workflows:
  ionic-capacitor-ios-build:
    name: Ionic Capacitor iOS Build
    instance_type: mac_mini_m1
    
    environment:
      node: v20.10.0
      xcode: latest
      vars:
        BUNDLE_ID: online.regionalhomeforgirls.larea
      
    scripts:
      - name: Install project dependencies
        script: |
          npm install
          
      - name: Check Capacitor config
        script: |
          ls -la capacitor.config.*
          cat capacitor.config.ts || cat capacitor.config.json || echo "No config found"
          
      - name: Sync Capacitor to iOS
        script: |
          npx cap sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      - name: Build iOS app (simulator)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
          
    artifacts:
      - ios/App/build/Build/Products/**/*.app
