workflows:
  ionic-capacitor-ios-build:
    name: Ionic Capacitor iOS Build
    instance_type: mac_mini_m1
    
    environment:
      node: v20.10.0
      xcode: latest
      vars:
        BUNDLE_ID: online.regionalhomeforgirls.larea
      
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @ionic/cli
          
      - name: Build the web app
        script: |
          npm run build --if-present || ionic build --prod
          
      - name: Sync Capacitor
        script: |
          npx cap sync ios
          
      - name: Set up code signing (temporary workaround)
        script: |
          cd ios/App
          pod install
          # Disable code signing for now
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' App.xcodeproj/project.pbxproj || true
          
      - name: Build iOS (unsigned)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -sdk iphonesimulator
          
    artifacts:
      - ios/App/build/**/*.app
