workflows:
  ionic-capacitor-ios-build:
    name: Ionic Capacitor iOS Build
    instance_type: mac_mini_m1
    
    environment:
      node: v20.10.0
      xcode: 15.3
      vars:
        BUNDLE_ID: online.regionalhomeforgirls.larea
      
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
          
      - name: Build the Ionic Web App
        script: |
          ionic build --prod
          
      - name: Copy web assets to iOS project
        script: |
          npx cap sync ios
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          
    artifacts:
      - ios/App/build/**/*.ipa
