workflows:
  ionic-capacitor-ios-build:
    name: Ionic Capacitor iOS Build
    instance_type: mac_mini_m1
    
    environment:
      node: v20.10.0
      xcode: latest
      vars:
        BUNDLE_ID: online.regionalhomeforgirls.larea
      
    scripts:
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
          
      - name: Sync Capacitor (use existing files)
        script: |
          npx cap sync ios || npx cap copy ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      - name: Build iOS app (simulator)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
          
    artifacts:
      - ios/App/build/Build/Products/**/*.app
